name: "Bug report!"
description: "Report a bug"
body:
  - type: dropdown
    attributes:
      label: "Which component went wrong?"
      options: ["The randomiser tool (pkc-mms-rando)", "The disassembly (rgbds)", "The game (ROM)", ]
    validations:
      required: true
  - type: textarea
    attributes:
      label: "How did it go wrong?"
      description: Describe the problem, the more details the better.
    validations:
      required: true
